// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"github.com/egon12/ghr/commit"
	"github.com/egon12/ghr/coverreview"
	"github.com/egon12/ghr/review"
	"github.com/google/go-github/v31/github"
	"github.com/shurcooL/githubv4"
)

// Injectors from wire.go:

func InitApp(config Config) *App {
	githubToken := ProvideGithubToken(config)
	tokenSource := ProvideOauthTokenSource(githubToken)
	client := ProvideOauthClient(tokenSource)
	githubv4Client := githubv4.NewClient(client)
	process := review.NewProcess(githubv4Client)
	githubClient := github.NewClient(client)
	multilineCommenter := review.NewMultilineCommenter(githubClient)
	source := commit.NewSource(githubv4Client)
	processFacade := review.NewProcessFacade(process, multilineCommenter, source)
	coverageReviewer := coverreview.NewCoverageReviewer(source, multilineCommenter)
	app := &App{
		ReviewProcess:    processFacade,
		CoverageReviewer: coverageReviewer,
	}
	return app
}
